spring:
  application:
    name: catalog-service
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 30
        max-interval: 20000
        multiplier: 1.3
  config:
    activate:
      on-profile: default
    import: configserver:http://config-server:8888

---
spring:
  application:
    name: catalog-service
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  data:
    mongodb:
      host: localhost
      username: catalog
      password: catalog
      port: 27018
      database: catalog_database
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true